name: build
on:
  pull_request:
    branches: [main]
    paths: ['**.cpp', '**.hpp', '**CMakeLists.txt']
  push:
    branches: [main]
    paths: ['**.cpp', '**.hpp', '**CMakeLists.txt']

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G 'Visual Studio 17 2022'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target 3d
